/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyekakhir.Admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import proyekakhir.ConnectDB;

/**
 *
 * @author Bagas A
 */
public class Acara extends javax.swing.JPanel {

    DefaultTableModel tbl;
    Connection con = ConnectDB.getConnection();
    Statement s = null;
    ResultSet rs;
    boolean row_Is_Selected = false;
    int index = 0;
    DefaultTableModel nav;

    /**
     * Creates new form Acara
     */
    public Acara() {
        initComponents();
        TampilData();
        try {
            s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = s.executeQuery("SELECT IDAcara, jenisAcara, paket, keterangan, estimasiHarga FROM Acara");
        } catch (Exception e) {
            // TODO: handle exception
        }
    }

    public void TampilData()
    {
        tbl = new DefaultTableModel();
        tbl.addColumn("ID Acara");
        tbl.addColumn("Jenis Acara");
        tbl.addColumn("Paket");
        tbl.addColumn("Keterangan");
        tbl.addColumn("Estimasi Harga");
        tableAcara.setModel(tbl);
        
        try {
            java.sql.Statement statement = con.createStatement();
            String sql = "SELECT * FROM Acara";
            java.sql.ResultSet result = statement.executeQuery(sql);
            while(result.next()) {
                tbl.addRow(new Object[] {
                    result.getString("IDAcara"),
                    result.getString("jenisAcara"),
                    result.getString("paket"),
                    result.getString("keterangan"),
                    result.getString("estimasiHarga")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        inputKeterangan = new javax.swing.JTextField();
        inputEstimasiHarga = new javax.swing.JTextField();
        inputJenisAcara = new javax.swing.JComboBox<>();
        inputPaket = new javax.swing.JComboBox<>();
        bSave = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bFirst1 = new javax.swing.JButton();
        bPrev1 = new javax.swing.JButton();
        bNext1 = new javax.swing.JButton();
        bLast1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAcara = new javax.swing.JTable();
        JBCari = new javax.swing.JButton();
        InputPencarian = new javax.swing.JTextField();
        CBTipeData = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1142, 521));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("INFORMASI ACARA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Jenis Acara");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Paket");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Keterangan");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("Estimasi Harga");

        inputJenisAcara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pernikahan", "Seminar", "Ulang Tahun", "Workshop" }));
        inputJenisAcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJenisAcaraActionPerformed(evt);
            }
        });

        inputPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputJenisAcara, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(inputEstimasiHarga))
                            .addComponent(inputPaket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJenisAcara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEstimasiHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        bSave.setBackground(new java.awt.Color(153, 153, 153));
        bSave.setText("SAVE");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bCancel.setBackground(new java.awt.Color(153, 153, 153));
        bCancel.setText("CANCEL");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bUpdate.setBackground(new java.awt.Color(153, 153, 153));
        bUpdate.setText("UPDATE");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bDelete.setBackground(new java.awt.Color(153, 153, 153));
        bDelete.setText("DELETE");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bFirst1.setBackground(new java.awt.Color(153, 153, 153));
        bFirst1.setText("<<");
        bFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFirst1ActionPerformed(evt);
            }
        });

        bPrev1.setBackground(new java.awt.Color(153, 153, 153));
        bPrev1.setText("<");
        bPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrev1ActionPerformed(evt);
            }
        });

        bNext1.setBackground(new java.awt.Color(153, 153, 153));
        bNext1.setText(">");
        bNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNext1ActionPerformed(evt);
            }
        });

        bLast1.setBackground(new java.awt.Color(153, 153, 153));
        bLast1.setText(">>");
        bLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLast1ActionPerformed(evt);
            }
        });

        tableAcara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAcara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAcaraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAcara);

        JBCari.setText("Cari");
        JBCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCariActionPerformed(evt);
            }
        });

        InputPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPencarianActionPerformed(evt);
            }
        });

        CBTipeData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Jenis Acara", "Paket", "Keterangan", "Estimasi Harga" }));
        CBTipeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTipeDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBTipeData, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBCari)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bPrev1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSave)
                            .addComponent(bUpdate)
                            .addComponent(bDelete)
                            .addComponent(bCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBTipeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bLast1)
                            .addComponent(bNext1)
                            .addComponent(bFirst1)
                            .addComponent(bPrev1))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        try {
            PreparedStatement statement = con.prepareStatement("INSERT INTO Acara (IDAcara, jenisAcara, paket, keterangan, estimasiHarga) VALUES (?, ?, ?, ?, ?)");
            
            statement.setString(1, inputID.getText());
            if(inputJenisAcara.getSelectedItem().equals("Pernikahan")) {
                statement.setString(2, "Pernikahan");
            } else if(inputJenisAcara.getSelectedItem().equals("Seminar")) {
                statement.setString(2, "Seminar");
            } else if(inputJenisAcara.getSelectedItem().equals("Ulang Tahun")) {
                statement.setString(2, "Ulang Tahun");
            } else if(inputJenisAcara.getSelectedItem().equals("Workshop")) {
                statement.setString(2, "Workshop");
            }
            if(inputPaket.getSelectedItem().equals("Paket 1")) {
                statement.setString(3, "Paket 1");
            } else if(inputPaket.getSelectedItem().equals("Paket 2")) {
                statement.setString(3, "Paket 2");
            } else if(inputPaket.getSelectedItem().equals("Paket 3")) {
                statement.setString(3, "Paket 3");
            }
            statement.setString(4, inputKeterangan.getText());
            statement.setString(5, inputEstimasiHarga.getText());

            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        inputID.setText("");
        inputJenisAcara.setSelectedIndex(0);
        inputPaket.setSelectedIndex(0);
        inputKeterangan.setText("");
        inputEstimasiHarga.setText("");
        buttonGroup1.clearSelection();
        InputPencarian.setText("");
        TampilData();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        try {
            PreparedStatement stmt = con.prepareStatement(
                "UPDATE Acara SET IDAcara=?, jenisAcara=?, paket=?, keterangan=?, estimasiHarga=? WHERE IDAcara=?");
            stmt.setString(1, inputID.getText());
            
            if(inputJenisAcara.getSelectedItem().equals("Pernikahan")) {
                stmt.setString(2, "Pernikahan");
            } else if(inputJenisAcara.getSelectedItem().equals("Seminar")) {
                stmt.setString(2, "Seminar");
            } else if(inputJenisAcara.getSelectedItem().equals("Ulang Tahun")) {
                stmt.setString(2, "Ulang Tahun");
            } else if(inputJenisAcara.getSelectedItem().equals("Workshop")) {
                stmt.setString(2, "Workshop");
            } else {
                JOptionPane.showMessageDialog(null, "Silahkan pilih bidang kerja yang tersedia!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(inputPaket.getSelectedItem().equals("Paket 1")) {
                stmt.setString(3, "Paket 1");
            } else if(inputPaket.getSelectedItem().equals("Paket 2")) {
                stmt.setString(3, "Paket 2");
            } else if(inputPaket.getSelectedItem().equals("Paket 3")) {
                stmt.setString(3, "Paket 3");
            } else {
                JOptionPane.showMessageDialog(null, "Silahkan pilih bidang kerja yang tersedia!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
            
            stmt.setString(4, inputKeterangan.getText());
            stmt.setString(5, inputEstimasiHarga.getText());
            stmt.setString(6, inputID.getText());

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        try {
            PreparedStatement stmt = con.prepareStatement(
                "DELETE FROM Acara WHERE IDAcara = '" + inputID.getText() + "'"
                + " AND jenisAcara = '" + inputJenisAcara.getSelectedItem() + "'"
                + " AND paket = '" + inputPaket.getSelectedItem() + "'"
                + " AND keterangan = '"+ inputKeterangan.getText()+ "'"
                + " AND estimasiHarga = '"+ inputEstimasiHarga.getText()+ "'");
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);

            inputID.setText("");
            inputJenisAcara.setSelectedItem("");
            inputPaket.setSelectedItem("");
            inputKeterangan.setText("");
            inputEstimasiHarga.setText("");
            buttonGroup1.clearSelection();
            TampilData();
        } catch (Exception e) {
            System.out.println("Error di sini");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void inputJenisAcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJenisAcaraActionPerformed
        if(inputJenisAcara.getSelectedItem().equals("Pernikahan")) {
            inputPaket.removeAllItems();
            inputPaket.setSelectedItem(null);
            inputPaket.addItem("Paket 1");
            inputPaket.addItem("Paket 2");
            inputPaket.addItem("Paket 3");
        } else if(inputJenisAcara.getSelectedItem().equals("Seminar")) {
            inputPaket.removeAllItems();
            inputPaket.setSelectedItem(null);
            inputPaket.addItem("Paket 1");
            inputPaket.addItem("Paket 2");
            inputPaket.addItem("Paket 3");
        } else if(inputJenisAcara.getSelectedItem().equals("Ulang Tahun")) {
            inputPaket.removeAllItems();
            inputPaket.setSelectedItem(null);
            inputPaket.addItem("Paket 1");
            inputPaket.addItem("Paket 2");
            inputPaket.addItem("Paket 3");
        } else if(inputJenisAcara.getSelectedItem().equals("Workshop")) {
            inputPaket.removeAllItems();
            inputPaket.setSelectedItem(null);
            inputPaket.addItem("Paket 1");
            inputPaket.addItem("Paket 2");
            inputPaket.addItem("Paket 3");
        }
    }//GEN-LAST:event_inputJenisAcaraActionPerformed

    private void bLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLast1ActionPerformed
        tableAcara.changeSelection(tableAcara.getRowCount() - 1, 0, false, false);
        highlightMouseClicked();
    }//GEN-LAST:event_bLast1ActionPerformed

    private void bNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNext1ActionPerformed
        int i = tableAcara.getSelectedRow();
        if (tableAcara.getRowCount() - 1 != i) {
            TableModel model = tableAcara.getModel();
            tableAcara.changeSelection(i+1, 0, false, false);
            highlightMouseClicked();
        }
    }//GEN-LAST:event_bNext1ActionPerformed

    private void bPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrev1ActionPerformed
        int i = tableAcara.getSelectedRow();
        TableModel model = tableAcara.getModel();
        tableAcara.changeSelection(i-1, 0, false, false);
        highlightMouseClicked();
    }//GEN-LAST:event_bPrev1ActionPerformed

    private void bFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFirst1ActionPerformed
        tableAcara.changeSelection(0, 0, false, false);
        highlightMouseClicked();
    }//GEN-LAST:event_bFirst1ActionPerformed

    private void InputPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPencarianActionPerformed

    }//GEN-LAST:event_InputPencarianActionPerformed

    private void JBCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCariActionPerformed
        tbl = new DefaultTableModel();
        tbl.addColumn("ID Acara");
        tbl.addColumn("Jenis Acara");
        tbl.addColumn("Paket");
        tbl.addColumn("Keterangan");
        tbl.addColumn("Estimasi Harga");
        tableAcara.setModel(tbl);

        String sql = "";
        try {
            java.sql.Statement st = con.createStatement();
            if(CBTipeData.getSelectedItem().equals("ID")) {
                String input = InputPencarian.getText();
                if (input.substring(input.length() - 1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE IDAcara LIKE '" + input.replace("%", "") + "%'";
                } else if (input.substring(0,1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE IDAcara LIKE '%" + input.replace("%", "") + "'";
                } else if (input.contains(input)) {
                    sql = "SELECT * FROM Acara WHERE IDAcara LIKE '%" + input + "%'";
                }
            } else if (CBTipeData.getSelectedItem().equals("Jenis Acara")) {
                String input = InputPencarian.getText();
                if (input.substring(input.length() - 1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE jenisAcara LIKE '" + input.replace("%", "") + "%'";
                } else if (input.substring(0,1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE jenisAcara LIKE '%" + input.replace("%", "") + "'";
                } else if (input.contains(input)) {
                    sql = "SELECT * FROM Acara WHERE jenisAcara LIKE '%" + input + "%'";
                }
            } else if (CBTipeData.getSelectedItem().equals("Paket")) {
                String input = InputPencarian.getText();
                if (input.substring(input.length() - 1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE paket LIKE '" + input.replace("%", "") + "%'";
                } else if (input.substring(0,1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE paket LIKE '%" + input.replace("%", "") + "'";
                } else if (input.contains(input)) {
                    sql = "SELECT * FROM Acara WHERE paket LIKE '%" + input + "%'";
                }
            } else if (CBTipeData.getSelectedItem().equals("Keterangan")) {
                String input = InputPencarian.getText();
                if (input.substring(input.length() - 1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE keterangan LIKE '" + input.replace("%", "") + "%'";
                } else if (input.substring(0,1).equals("%")) {
                    sql = "SELECT * FROM Acara WHERE keterangan LIKE '%" + input.replace("%", "") + "'";
                } else if (input.contains(input)) {
                    sql = "SELECT * FROM Acara WHERE keterangan LIKE '%" + input + "%'";
                }
            } else {
                sql = "SELECT * FROM Acara WHERE estimasiHarga LIKE '%" + InputPencarian.getText() + "%'";
            }

            java.sql.ResultSet res = st.executeQuery(sql);
            while (res.next()) {
                tbl.addRow(new Object[] {
                    res.getString("IDAcara"),
                    res.getString("jenisAcara"),
                    res.getString("paket"),
                    res.getString("keterangan"),
                    res.getString("estimasiHarga")
                });
            }
            inputID.setText("");
            inputJenisAcara.setSelectedIndex(0);
            inputPaket.setSelectedIndex(0);
            inputKeterangan.setText("");
            inputEstimasiHarga.setText("");
            buttonGroup1.clearSelection();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_JBCariActionPerformed

    private void CBTipeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTipeDataActionPerformed
        //     // TODO add your handling code here:
    }//GEN-LAST:event_CBTipeDataActionPerformed

    private void tableAcaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAcaraMouseClicked
        int row = tableAcara.getSelectedRow();
        inputID.setText(tableAcara.getValueAt(row, 0).toString());
        inputJenisAcara.setSelectedItem(tableAcara.getValueAt(row, 1).toString());
        inputPaket.setSelectedItem(tableAcara.getValueAt(row, 2).toString());
        inputKeterangan.setText(tableAcara.getValueAt(row, 3).toString());
        inputEstimasiHarga.setText(tableAcara.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tableAcaraMouseClicked
    
    private void highlightMouseClicked() {
        int row = tableAcara.getSelectedRow();
        inputID.setText(tableAcara.getValueAt(row, 0).toString());
        inputJenisAcara.setSelectedItem(tableAcara.getValueAt(row, 1).toString());
        inputPaket.setSelectedItem(tableAcara.getValueAt(row, 2).toString());
        inputKeterangan.setText(tableAcara.getValueAt(row, 3).toString());
        inputEstimasiHarga.setText(tableAcara.getValueAt(row, 4).toString());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBTipeData;
    private javax.swing.JTextField InputPencarian;
    private javax.swing.JButton JBCari;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bFirst1;
    private javax.swing.JButton bLast1;
    private javax.swing.JButton bNext1;
    private javax.swing.JButton bPrev1;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputEstimasiHarga;
    private javax.swing.JTextField inputID;
    private javax.swing.JComboBox<String> inputJenisAcara;
    private javax.swing.JTextField inputKeterangan;
    private javax.swing.JComboBox<String> inputPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAcara;
    // End of variables declaration//GEN-END:variables
}
